imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    image: default-bionic
    nodes:
        my-tests:
            environment:
                php:
                    version: 8.1.8
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    tests:
        override:
            -
                # command: "composer phpunit"
                command: "php bin/console --env=test doctrine:database:create &&  
                        php bin/console --env=test doctrine:schema:create && 
                        php bin/console doctrine:fixtures:load -y &&
                        XDEBUG_MODE=coverage vendor/bin/phpunit"
                coverage:
                    file: "build/coverage.clover"
                    format: "php-clover"
